# Фильтрация и выборка данных в Pandas

### Импорт библиотек и подготовка данных

In [2]:
# Импортируем библиотеки
import pandas as pd

In [3]:
# Создадим тестовый датасет о погоде
df = pd.read_excel('weather.xlsx',header = None)
df.columns = ['date','temp','hum']
df

C:\Users\Светлана\AppData\Local\Temp\ipykernel_1828\1987778680.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.header = ['date','temp','hum']

             0   1   2
0   2024-12-02 -10  96
1   2024-12-03  -3  57
2   2024-12-04  -2  89
3   2024-12-05  -5  99
4   2024-12-06  -8  50
..         ...  ..  ..
361 2025-11-28  -9  97
362 2025-11-29  -7  92
363 2025-11-30  -3  58
364 2025-12-01  -5  71
365 2025-12-02  -4  89

[366 rows x 3 columns]

---
## 1. Выборка колонок

### Способы выбора колонок:

1. **Одна колонка**: `df['column_name']` или `df.column_name` → возвращает Series
2. **Несколько колонок**: `df[['col1', 'col2']]` → возвращает DataFrame
3. **Все колонки кроме некоторых**: `df.drop(['col1'], axis=1)`

### Пример 1: Выбор одной колонки

In [9]:
# Выберите колонку с температурой
df.drop(['temp'],axis=1)

          date  hum
0   2024-12-02   96
1   2024-12-03   57
2   2024-12-04   89
3   2024-12-05   99
4   2024-12-06   50
..         ...  ...
361 2025-11-28   97
362 2025-11-29   92
363 2025-11-30   58
364 2025-12-01   71
365 2025-12-02   89

[366 rows x 2 columns]

### Пример 2: Выбор нескольких колонок

In [ ]:
# Выберите только дату, температуру и осадки

---
## 2. Индексация: loc vs iloc

### loc - доступ по МЕТКАМ (labels)
- Использует названия строк и столбцов
- Синтаксис: `df.loc[rows, columns]`
- Включает конечное значение в срез

### iloc - доступ по ПОЗИЦИЯМ (integer positions)
- Использует числовые индексы (0, 1, 2, ...)
- Синтаксис: `df.iloc[rows, columns]`
- НЕ включает конечное значение (как обычный Python срез)

### Когда что использовать?
- **loc**: когда знаете название/метку ("дайте строку с датой 2024-01-15")
- **iloc**: когда знаете позицию ("дайте 5-ую строку")

### Пример 3: Использование loc

In [14]:
# Выберите конкретную строку по индексу
# Выберите диапазон строк
# Выберите строки и колонки одновременно
df2 = df.loc[100:200]
df2

          date  temp  hum
100 2025-03-12    -4   64
101 2025-03-13    -7   72
102 2025-03-14     1   88
103 2025-03-15   -10   90
104 2025-03-16    -7   56
..         ...   ...  ...
196 2025-06-16    -5   51
197 2025-06-17    -5   53
198 2025-06-18    -2   59
199 2025-06-19     2   61
200 2025-06-20     1   70

[101 rows x 3 columns]

### Пример 4: Использование iloc

In [20]:
# Выберите первую строку
# Выберите первые 5 строк
# Выберите конкретные строки и столбцы по позициям
df2.iloc[0]

date    2025-03-12 00:00:00
temp                     -4
hum                      64
Name: 100, dtype: object

---
## 3. Булева индексация (Boolean Indexing)

**Булева индексация** — это фильтрация данных по условию.

### Как это работает:
1. Создаем условие (например, `df['Temperature'] > 25`)
2. Получаем Series из True/False
3. Используем эту Series для фильтрации: `df[condition]`

### Операторы сравнения:
- `==` равно
- `!=` не равно
- `>` больше
- `<` меньше
- `>=` больше или равно
- `<=` меньше или равно

### Пример 5: Простая фильтрация

In [27]:
# Найдите все дни, когда температура была выше 25°C
df.loc[df['temp'] > 0]

          date  temp  hum
5   2024-12-07     4   77
6   2024-12-08     1   96
8   2024-12-10     3   83
12  2024-12-14     4   60
18  2024-12-20     3   50
..         ...   ...  ...
347 2025-11-14     2   68
348 2025-11-15     4   90
352 2025-11-19     3   57
354 2025-11-21     3   72
355 2025-11-22     1   67

[94 rows x 3 columns]

### Пример 6: Фильтрация с объяснением шагов

In [ ]:
# Шаг 1: Создайте условие
# Шаг 2: Посмотрите на результат (Series из True/False)
# Шаг 3: Примените фильтр к DataFrame

---
## 4. Сложные условия

### Логические операторы:
- `&` - И (AND) - оба условия должны быть True
- `|` - ИЛИ (OR) - хотя бы одно условие True
- `~` - НЕ (NOT) - инверсия условия

### ВАЖНО:
Каждое условие должно быть в скобках!
```python
# Правильно:
df[(df['Temperature'] > 20) & (df['Humidity'] < 70)]

# Неправильно:
df[df['Temperature'] > 20 & df['Humidity'] < 70]
```

### Пример 7: Условие И (AND)

In [30]:
# Найдите дни с температурой выше 20°C И влажностью ниже 70%
df[~((df['temp'] > 0) | (df['hum'] > 70))]

          date  temp  hum
1   2024-12-03    -3   57
4   2024-12-06    -8   50
7   2024-12-09    -9   69
9   2024-12-11    -6   69
10  2024-12-12    -4   57
..         ...   ...  ...
351 2025-11-18    -9   61
353 2025-11-20    -8   66
358 2025-11-25    -7   63
360 2025-11-27    -5   53
363 2025-11-30    -3   58

[118 rows x 3 columns]

### Пример 8: Условие ИЛИ (OR)

In [35]:
# Найдите дни с очень низкой (< 15°C) ИЛИ очень высокой (> 30°C) температурой
df[(df['temp'] < -7) | (df['temp'] > 2)]

          date  temp  hum
0   2024-12-02   -10   96
4   2024-12-06    -8   50
5   2024-12-07     4   77
7   2024-12-09    -9   69
8   2024-12-10     3   83
..         ...   ...  ...
352 2025-11-19     3   57
353 2025-11-20    -8   66
354 2025-11-21     3   72
359 2025-11-26    -9   85
361 2025-11-28    -9   97

[142 rows x 3 columns]

### Пример 9: Условие НЕ (NOT)

In [38]:
# Найдите дни без осадков (осадки == 0)
# Затем найдите дни С осадками, используя NOT
df[~(df.temp == 0)]

          date  temp  hum
0   2024-12-02   -10   96
1   2024-12-03    -3   57
2   2024-12-04    -2   89
3   2024-12-05    -5   99
4   2024-12-06    -8   50
..         ...   ...  ...
361 2025-11-28    -9   97
362 2025-11-29    -7   92
363 2025-11-30    -3   58
364 2025-12-01    -5   71
365 2025-12-02    -4   89

[346 rows x 3 columns]

### Пример 10: Проверка на вхождение в список (.isin())

In [41]:
# Найдите дни с определенным описанием погоды
# Например: только 'Ясно' или 'Облачно'
df[df.temp.isin([-10,4,0])]

          date  temp  hum
0   2024-12-02   -10   96
5   2024-12-07     4   77
12  2024-12-14     4   60
13  2024-12-15   -10   95
14  2024-12-16   -10   82
..         ...   ...  ...
332 2025-10-30     0   65
334 2025-11-01     0   77
338 2025-11-05     4   60
344 2025-11-11   -10   53
348 2025-11-15     4   90

[74 rows x 3 columns]

---
## 5. Сортировка данных

### Метод .sort_values()
Сортирует DataFrame по значениям в колонке(ах).

**Параметры:**
- `by`: имя колонки или список колонок
- `ascending`: True (по возрастанию) или False (по убыванию)
- `inplace`: False (вернуть новый DF) или True (изменить исходный)

### Метод .sort_index()
Сортирует DataFrame по индексу.

### Пример 11: Сортировка по одной колонке

In [ ]:
# Отсортируйте данные по температуре (от холодной к теплой)

### Пример 12: Сортировка по убыванию

In [ ]:
# Отсортируйте по температуре от самой теплой к самой холодной

### Пример 13: Сортировка по нескольким колонкам

In [ ]:
# Отсортируйте сначала по описанию, затем по температуре

---
## 6. Метод .query()

**Альтернативный способ фильтрации** с более читаемым синтаксисом.

```python
# Вместо:
df[(df['Temperature'] > 25) & (df['Humidity'] < 70)]

# Можно:
df.query('Temperature > 25 and Humidity < 70')
```

Удобно для сложных запросов!

### Пример 14: Использование .query()

In [ ]:
# Используйте .query() для поиска комфортных дней:
# Температура 20-25°C, влажность < 70%, без осадков

---
## 7. Практические задачи

Теперь ваша очередь! Примените изученные методы.

### Задача 1: Базовая фильтрация

**Задание**: Используя датасет о погоде:
1. Найдите все дни с температурой ниже 20°C
2. Найдите дни с влажностью выше 80%
3. Найдите дни с осадками больше 5 мм
4. Посчитайте, сколько таких дней в каждом случае (.shape[0] или len())

In [ ]:
# Ваш код здесь

### Задача 2: Сложные условия

**Задание**: 
1. Найдите дни с температурой от 22 до 28°C (включительно)
2. Найдите дождливые дни (описание = 'Дождь') с температурой выше 20°C
3. Найдите дни, которые НЕ были ясными (описание != 'Ясно')
4. Найдите дни с высокой влажностью (>75%) ИЛИ осадками (>0)

**Подсказка**: используйте &, |, ~ и скобки

In [ ]:
# Ваш код здесь

### Задача 3: Использование loc и iloc

**Задание**:
1. Выберите строки с 10 по 20 используя iloc
2. Выберите первые 5 строк и только колонки 'Date', 'Temperature', 'Description'
3. Выберите последние 10 строк датасета
4. Выберите каждую 5-ую строку (используйте срез с шагом)

**Подсказка**: срезы работают так же как в списках Python

In [ ]:
# Ваш код здесь

### Задача 4: Топ-N значений

**Задание**:
1. Найдите топ-10 самых жарких дней (отсортируйте и возьмите первые 10)
2. Найдите топ-5 дней с наибольшими осадками
3. Найдите 10 дней с самой низкой влажностью
4. Для каждого случая выведите дату, температуру и соответствующий показатель

**Подсказка**: используйте .sort_values() и .head()

In [ ]:
# Ваш код здесь

### Задача 5: Комбинированный анализ

**Задание**: Проанализируйте "идеальные дни" для прогулки:
- Температура: 20-26°C
- Влажность: меньше 65%
- Ветер: меньше 15 км/ч
- Осадки: 0 мм

1. Отфильтруйте данные по всем этим условиям
2. Посчитайте, сколько таких дней
3. Выведите эти дни, отсортированные по температуре
4. Найдите среднюю температуру в эти "идеальные" дни

In [ ]:
# Ваш код здесь

### Задача 6: Работа с .isin() и .query()

**Задание**:
1. Используя .isin(), найдите дни с описанием 'Ясно' или 'Облачно'
2. Используя .query(), найдите дни с температурой 23-27°C и ветром < 20 км/ч
3. Сравните, какой способ вам удобнее

**Подсказка**: в .query() используйте `and` вместо `&`

In [ ]:
# Ваш код здесь

---
## 8. Дополнительные задачи (*)

Для тех, кто справился быстрее:

### Задача 7*: Анализ по сезонам

**Задание**: Если у вас есть колонка с датами:
1. Извлеките месяц из даты (используйте .dt.month)
2. Создайте новую колонку 'Season':
   - Зима: 12, 1, 2
   - Весна: 3, 4, 5
   - Лето: 6, 7, 8
   - Осень: 9, 10, 11
3. Найдите самый жаркий день в каждом сезоне
4. Найдите среднюю температуру по сезонам

**Подсказка**: используйте функцию или словарь для маппинга месяцев на сезоны

In [ ]:
# Ваш код здесь

### Задача 8*: Поиск паттернов

**Задание**: Найдите "аномальные" дни:
1. Вычислите среднюю температуру и стандартное отклонение
2. Аномалия = температура отклоняется от средней более чем на 2 стандартных отклонения
3. Найдите все такие дни
4. Определите, это "аномально жаркие" или "аномально холодные" дни

**Подсказка**: используйте .mean() и .std(), затем булеву индексацию

In [ ]:
# Ваш код здесь

### Задача 9*: Цепочка операций

**Задание**: Напишите одну цепочку операций (method chaining), которая:
1. Фильтрует дни с температурой > 20°C
2. Выбирает только колонки Date, Temperature, Humidity
3. Сортирует по влажности по возрастанию
4. Берет первые 10 строк

Все это должно быть в одной строке с использованием точечной нотации!

**Подсказка**: используйте \ для переноса длинных строк

In [ ]:
# Ваш код здесь